/*
 Copyright (c) 2016, David lu
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright
 notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.
 * Neither the name of the <organization> nor the
 names of its contributors may be used to endorse or promote products
 derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef OPS_DEFINITION_H_
#define OPS_DEFINITION_H_

namespace cacu {

/**
 * op definition
 * every operation is defined here and registered in operator_factory.h
 */

enum op_name {
	CACU_INNERPRODUCT,
	CACU_CONVOLUTION,
	CACU_L_INNERPRODUCT,
	CACU_BATCH_NORMALIZE,
	CACU_INSTANCE_NORMALIZE,
	CACU_SPATIAL_INSTANCE_NORMALIZE,
	CACU_CONDITIONAL_BN,
	CACU_CONDITIONAL_IN,
	CACU_ADDIN,
	CACU_DROPOUT,
	CACU_P_INNERPRODUCT,
	CACU_DECONVOLUTION,
	CACU_CONV_TRANS,
	CACU_LOCAL_CONV,
	CACU_NORM,
	CACU_SN_INNERPRODUCT,
	CACU_SN_CONVOLUTION,
	CACU_WN_CONVOLUTION,
	CACU_E_CONVOLUTION,
	CACU_E_INNERPRODUCT,
	CACU_E_CONV_TRANS,
	CACU_BLUR,

	CACU_ROW_MAX_POOLING,
	CACU_MAX_POOLING,
	CACU_AVERAGE_POOLING,
	CACU_ROI_POOLING,
	CACU_UN_POOLING,

	CACU_RELU,
	CACU_LEAKY_RELU,
	CACU_PRELU,
	CACU_SOFTMAX,
	CACU_TANH,
	CACU_HTANH,
	CACU_SIGMOID,
	CACU_SOFTPLUS,
	CACU_ELU,
	CACU_SELU,
	CACU_SIGMOID_SIGN,
	CACU_MISH,

	CACU_SOFTMAX_LOSS,
	CACU_MSE_LOSS,
	CACU_HINGE_LOSS,
	CACU_MULTI_CE_LOSS,
	CACU_SIGMOID_LOSS,
	CACU_ABSE_LOSS,
	CACU_TRIPLET_LOSS,
	CACU_CE_LOSS,
	CACU_FOCAL_SOFTMAX_LOSS,
	CACU_CENTER_LOSS,

	CACU_SUM_ELEMWISE,
	CACU_FEATURE_COMBINE,
	CACU_SPLIT,
	CACU_SHUFFLE_CHANNEL,
	CACU_P_SUM_ELEMWISE,

	CACU_CONDITIONAL_PROJECTION,
	CACU_IP_PROJECTION,
	CACU_SN_IP_PROJECTION,
	CACU_INJECTOR,

	CACU_PRIMARY_VECTOR,
	CACU_COMBINATION,
	CACU_CONCENTRATE,

	CACU_MATH_ADD,
	CACU_MATH_SUB,
	CACU_MATH_MUL,
	CACU_MATH_AXPBY,
	CACU_MATH_SCALEX,
	CACU_MATH_MEAN,
	CACU_MATH_ABS,

	CACU_NULL
};


/*
 * operator base type
 */

enum base_type {
	LOSS_BASE,
	POOLING_BASE,
	CONV_BASE,
	ACTIVATION_BASE,
	MATH_BASE,
	BN_BASE,
	NULL_BASE
};


/**
* math op definition
* Introduced by math_op
*/

enum math_op_name {
	ADD,
	SUB,
	MUL,
	DIV,
	ABS,
	MASK_LT,
	MASK_GT
};



}


#endif
